### ISSUE TITLE
I had problem with the key.0

### ISSUE THREAD

**Issue by jovanonymous** [woosal1337/Chegg-Discord-BOT#10]
As you published the discord bot of chegg, the package not included with key.0 and token.0. So I personally added it manually with notepad and saved it as (.0) extension. But you are told us to fill the token.0 with the token of the Bot, but for the key.0 you never notice of it so I'm only make the key.0 with nothing on it (0 kb). I wonder what inside of it

**Comment by woosal1337** [comment]
I think there is something wrong with your installation, again, even now if you would check key.0 in my repo it is there and exists. Make sure to correctly* download all the files without any corruption. Thanks!

**Comment by jovanonymous** [comment]
But you posted it without the key.0

https://prnt.sc/10edzrq

**Comment by woosal1337** [comment]
Mate, you are in the wrong directory. Head over https://github.com/woosal1337/Chegg
