### ISSUE TITLE
Sorry for spamming

### ISSUE THREAD

**Issue by jovanonymous** [woosal1337/Chegg-Discord-BOT#11]
I would like to charge a payment of voulenteers if you can help me personally by discord or something. Please help me..

**Comment by woosal1337** [comment]
What do you mean?

**Comment by jovanonymous** [comment]
To help fix my problem, I would like to pay for it

**Comment by woosal1337** [comment]
What is your issue? There is no need for payment, just mention briefly and precisely here, please.
