### ISSUE TITLE
A problem with +addmail

### ISSUE THREAD

**Issue by jovanonymous** [woosal1337/Chegg-Discord-BOT#8]
The program was connected by :
"Committing...
Running Setup...
fun
fun was loaded!
Setup Completed!
Running bot...
BOT has been CONNECTED!"

But when I try to +addmail it doesn't message me

**Comment by woosal1337** [comment]
Make sure you have configured FireBase correctly, and integrated right.

**Comment by jovanonymous** [comment]
Found the solution thank you
