### ISSUE TITLE
A Problem Stuck with I am searching for the answer, please give me a few seconds!

### ISSUE THREAD

**Issue by jovanonymous** [woosal1337/Chegg-Discord-BOT#9]
How can I fix the bot not sending the response due the email

**Comment by woosal1337** [comment]
Could you specify your issue more precisely please? What do you mean due the email?

**Comment by jovanonymous** [comment]
I already found the solution of it but I got another problem due to success false INVALID TOKEN, I assume the problem was from the key.0. Could you tell me what is inside the key.0

**Comment by woosal1337** [comment]
Invalid Token means your Discord bot's token is wrong. key.0 is always right as it is associated with woosal.com website hosting and API.
